import React, { useMemo, useState } from "react";
import { LayoutAnimation, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { Ban, CalendarDays, ChevronDown, ChevronUp, Eye, Filter, Lock, LockOpen, Pencil, Plus, Printer, RefreshCw, Search, Trash2, WalletCards } from "lucide-react-native";
import { ThemedText } from "@/components/ThemedText";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { IconButton } from "@/components/ui/IconButton";
import { SearchBar } from "@/components/ui/SearchBar";
import { Select } from "@/components/ui/Select";
import { TabBar } from "@/components/ui/TabBar";
import { Modal } from "@/components/ui/Modal";
import { useTheme } from "@/theme/useTheme";
import { useArqueoAbierto } from "../hooks/useArqueoAbierto";
import { useArqueos } from "../hooks/useArqueos";
import { useIngresos, useEgresos } from "../hooks/useMovimientos";
import { useTiposTransaccion } from "../hooks/useTiposTransaccion";
import { AbrirArqueoModal } from "./AbrirArqueoModal";
import { DetalleArqueoModal } from "./DetalleArqueoModal";
import { MovimientoFormModal } from "./MovimientoFormModal";
import { MovimientoPrintModal } from "./MovimientoPrintModal";
import { ArqueoPrintModal } from "./ArqueoPrintModal";
import { TipoTransaccionFormModal } from "./TipoTransaccionFormModal";
import { RangoAperturaFilter } from "./RangoFechaFilter";
import { ConfirmModal, useConfirmLocal } from "./ConfirmModal";
import { useArqueoStore } from "../store/arqueoStore";
import type { Arqueo, Egreso, EstadoArqueo, EstadoMovimiento, Ingreso, NaturalezaTransaccion, TipoPago, TipoTransaccion } from "../types/arqueo.types";
import { num } from "../types/arqueo.types";

type TabKey = "arqueos" | "ingresos" | "egresos" | "tipos";
const tabs = [{key:"arqueos",label:"Arqueos"},{key:"ingresos",label:"Ingresos"},{key:"egresos",label:"Egresos"},{key:"tipos",label:"Tipos"}];
const iso = (d: Date) => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const short = (d: Date) => `${d.getDate()} ${["Ene","Feb","Mar","Abr","May","Jun","Jul","Ago","Sep","Oct","Nov","Dic"][d.getMonth()]}`;
function nombre(a: Arqueo){ const u=a.user; const n=`${u?.nombres??""} ${u?.primer_apellido??""}`.trim(); return n||u?.usuario||`Usuario ${a.id_user}`; }

export function ArqueoMobileView(){
 const {theme}=useTheme(); const c=theme.colors; const [tab,setTab]=useState<TabKey>("arqueos");
 const [movTotal,setMovTotal]=useState(0);
 const {abierto,refreshing,refrescar}=useArqueoAbierto(true); const [abrir,setAbrir]=useState(false); const [detalle,setDetalle]=useState<number|null>(null); const fetchAbierto=useArqueoStore(s=>s.fetchAbierto);
 const showMovTotal=tab==="ingresos"||tab==="egresos";
 return <View style={[s.root,{backgroundColor:c.background}]}>
  <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={[s.page,{paddingBottom:showMovTotal?150:100}]}>
   <View style={[s.head,{backgroundColor:c.backgroundSecondary,borderColor:c.border}]}><View style={s.headLeft}><View style={[s.iconBox,{backgroundColor:c.primary+"18"}]}><WalletCards size={21} color={c.primary}/></View><View><ThemedText style={s.headTitle}>Arqueo de caja</ThemedText><ThemedText style={[s.headSub,{color:c.textSecondary}]}>{abierto?`Caja abierta #${abierto.id}`:"Sin arqueo abierto"}</ThemedText></View></View><View style={s.headActions}><IconButton icon={RefreshCw} size="sm" variant="secondary" loading={refreshing} accessibilityLabel="Actualizar" onPress={()=>void refrescar()}/><Button title={abierto?"Ver caja":"Abrir"} onPress={()=>abierto?setDetalle(abierto.id):setAbrir(true)}/></View></View>
   <TabBar tabs={tabs} activeTab={tab} onTabChange={k=>setTab(k as TabKey)}/>
   {tab==="arqueos"?<ArqueosMobile onDetalle={setDetalle}/>:tab==="ingresos"?<MovMobile kind="ingreso" onTotalChange={setMovTotal}/>:tab==="egresos"?<MovMobile kind="egreso" onTotalChange={setMovTotal}/>:<TiposMobile/>}
  </ScrollView>
  {tab==="arqueos"?<Pressable accessibilityRole="button" accessibilityLabel={abierto?"Cerrar arqueo":"Abrir arqueo"} onPress={()=>abierto?setDetalle(abierto.id):setAbrir(true)} style={[s.floatingArqueo,{backgroundColor:abierto?"#EF4444":"#16A34A"}]}>{abierto?<Lock size={19} color="#fff"/>:<LockOpen size={19} color="#fff"/>}<Text style={s.floatingArqueoText}>{abierto?"Cerrar Arqueo":"Abrir Arqueo"}</Text></Pressable>:null}
  {showMovTotal?<View style={[s.fixedTotal,{backgroundColor:c.backgroundSecondary,borderColor:c.border}]}><View><ThemedText style={{color:c.textSecondary,fontWeight:"900"}}>{tab==="ingresos"?"TOTAL INGRESOS:":"TOTAL EGRESOS:"}</ThemedText></View><ThemedText style={s.totalText}>Bs. {movTotal.toFixed(2)}</ThemedText></View>:null}
  <AbrirArqueoModal visible={abrir} onClose={()=>setAbrir(false)}/><DetalleArqueoModal visible={detalle!==null} arqueoId={detalle} onClose={()=>setDetalle(null)} onClosed={()=>void fetchAbierto(true)}/>
 </View>
}

function DateStrip({desde,hasta,onApply}:{desde:string;hasta:string;onApply:(a:string,b:string)=>void}){ const {theme}=useTheme(); const c=theme.colors; const [modal,setModal]=useState(false); const today=new Date(); const ds=[2,1,0].map(n=>{const d=new Date(today);d.setDate(d.getDate()-n);return d}); return <><View style={s.dateRow}>{ds.map(d=>{const v=iso(d),active=desde===v&&hasta===v;return <Pressable key={v} onPress={()=>onApply(v,v)} style={[s.dateChip,{borderColor:c.border,backgroundColor:active?c.primary:c.backgroundSecondary}]}><Text style={{color:active?"#111":c.text,fontWeight:"800",fontSize:12}}>{short(d)}</Text></Pressable>})}<IconButton icon={CalendarDays} size="sm" variant="secondary" accessibilityLabel="Fecha o rango" onPress={()=>setModal(true)}/></View><Modal visible={modal} onClose={()=>setModal(false)} title="Fecha o rango" maxWidth={420}><RangoAperturaFilter desde={desde} hasta={hasta} onApply={(a,b)=>{onApply(a,b);setModal(false)}} onClear={()=>{onApply("","");setModal(false)}}/></Modal></> }

function ArqueosMobile({onDetalle}:{onDetalle:(id:number)=>void}){ const {theme}=useTheme(); const c=theme.colors; const h=useArqueos(); const confirm=useConfirmLocal(); const [expanded,setExpanded]=useState<number|null>(null); const [filter,setFilter]=useState(false); const [print,setPrint]=useState<Arqueo|null>(null); const today=iso(new Date()); React.useEffect(()=>{if(!h.fechaDesde&&!h.fechaHasta){h.setFechaDesde(today);h.setFechaHasta(today)}},[]);
 return <View style={s.section}><DateStrip desde={h.fechaDesde} hasta={h.fechaHasta} onApply={(a,b)=>{h.setFechaDesde(a);h.setFechaHasta(b);h.setPage(1)}}/><View style={s.searchRow}><View style={{flex:1}}><SearchBar value="" onChangeText={()=>{}} placeholder="Arqueos por fecha y estado"/></View><IconButton icon={Filter} variant="secondary" accessibilityLabel="Filtros" onPress={()=>setFilter(true)}/></View>
 <View style={s.cards}>{h.items.map(a=><Pressable key={a.id} onPress={()=>{LayoutAnimation.configureNext({duration:360,create:{type:LayoutAnimation.Types.easeInEaseOut,property:LayoutAnimation.Properties.opacity},update:{type:LayoutAnimation.Types.easeInEaseOut},delete:{type:LayoutAnimation.Types.easeInEaseOut,property:LayoutAnimation.Properties.opacity}});setExpanded(expanded===a.id?null:a.id)}} style={[s.compactCard,{backgroundColor:c.backgroundSecondary,borderColor:c.border}]}><View style={s.cardTop}><View style={s.cardMain}><WalletCards size={19} color={c.primary}/><View><ThemedText style={s.cardTitle}>Arqueo #{a.id}</ThemedText><ThemedText style={[s.cardSub,{color:c.textSecondary}]}>{nombre(a)}</ThemedText></View></View><View style={s.cardRight}><ThemedText style={s.amount}>Bs. {num(a.total_general??a.saldo_anterior).toFixed(2)}</ThemedText><Badge label={a.estado} variant={a.estado==="Iniciado"?"success":"muted"}/></View></View>{expanded===a.id?<View style={[s.expand,{borderTopColor:c.border}]}><KV k="Apertura" v={String(a.fecha_apertura).slice(0,16).replace("T"," ")}/><KV k="Cajero" v={nombre(a)}/><KV k="Saldo anterior" v={`Bs. ${num(a.saldo_anterior).toFixed(2)}`}/><View style={[s.expandedActions,{borderTopColor:c.border}]}><IconButton icon={Eye} size="md" variant="secondary" accessibilityLabel="Ver caja" onPress={()=>onDetalle(a.id)}/><IconButton icon={Printer} size="md" variant="secondary" accessibilityLabel="Imprimir arqueo" onPress={()=>setPrint(a)}/>{a.estado==="Iniciado"?<IconButton icon={Lock} size="md" variant="secondary" accessibilityLabel="Cerrar arqueo" onPress={()=>onDetalle(a.id)}/>:null}{a.estado==="Terminado"?<IconButton icon={Trash2} size="md" variant="destructive" accessibilityLabel="Eliminar" onPress={async()=>{const ok=await confirm.ask({title:"Eliminar arqueo",message:`¿Eliminar arqueo #${a.id}?`,variant:"danger",confirmText:"Eliminar"});if(ok)await h.eliminar(a.id);confirm.closeConfirm()}}/>:null}</View></View>:null}</Pressable>)}</View><View style={s.pager}><ThemedText style={{color:c.textSecondary}}>Mostrando {h.items.length} de {h.total}</ThemedText></View>
 <ArqueoPrintModal visible={print!==null} arqueo={print} onClose={()=>setPrint(null)}/><Modal visible={filter} onClose={()=>setFilter(false)} title="Filtrar arqueos"><Select<EstadoArqueo|""> label="Estado" value={h.estado} options={[{label:"Todos",value:""},{label:"Iniciado",value:"Iniciado"},{label:"Terminado",value:"Terminado"}]} onValueChange={v=>{h.setEstado(v);h.setPage(1)}} modalTitle="Estado"/><View style={{height:12}}/><Button title="Ver resultados" onPress={()=>setFilter(false)}/></Modal><ConfirmModal state={confirm.confirmState} busy={confirm.confirmBusy} onCancel={confirm.handleCancel} onConfirm={confirm.handleConfirm}/></View>
}

function KV({k,v}:{k:string;v:string}){const {theme}=useTheme();return <View style={s.kv}><ThemedText style={{color:theme.colors.textSecondary,fontSize:12}}>{k}</ThemedText><ThemedText style={s.kvv}>{v}</ThemedText></View>}

function MovMobile({kind,onTotalChange}:{kind:"ingreso"|"egreso";onTotalChange:(total:number)=>void}){ const {theme}=useTheme(); const c=theme.colors; const h=kind==="ingreso"?useIngresos():useEgresos(); const [expanded,setExpanded]=useState<number|null>(null); const [filter,setFilter]=useState(false); const [form,setForm]=useState(false); const [print,setPrint]=useState<Ingreso|Egreso|null>(null); const confirm=useConfirmLocal(); const [q,setQ]=useState(""); const es=kind==="ingreso"; const today=iso(new Date()); React.useEffect(()=>{if(!h.fechaDesde&&!h.fechaHasta){h.setFechaDesde(today);h.setFechaHasta(today)}},[]); const filtrados=h.items.filter(m=>!q.trim()||String(m.id_arqueo).includes(q.trim())||m.detalle.toLowerCase().includes(q.toLowerCase())); const totalMonto=filtrados.filter(m=>m.estado!=="Anulado").reduce((x,m)=>x+num(m.monto),0); React.useEffect(()=>{onTotalChange(totalMonto)},[totalMonto,onTotalChange]);
 return <View style={s.section}><DateStrip desde={h.fechaDesde} hasta={h.fechaHasta} onApply={(a,b)=>{h.setFechaDesde(a);h.setFechaHasta(b);h.setPage(1)}}/><View style={s.mobileToolbar}><View><ThemedText style={s.listTitle}>{es?"Ingresos":"Egresos"}</ThemedText><ThemedText style={{color:c.textSecondary,fontSize:12}}>{h.total} registros</ThemedText></View><View style={s.actionRow}><IconButton icon={RefreshCw} size="sm" variant="secondary" accessibilityLabel="Actualizar" onPress={()=>void h.refrescar()}/><IconButton icon={Plus} variant="primary" accessibilityLabel={es?"Nuevo ingreso":"Nuevo egreso"} onPress={()=>setForm(true)}/></View></View><View style={s.searchRow}><View style={{flex:1}}><SearchBar value={q} onChangeText={setQ} placeholder="Buscar movimiento o arqueo..."/></View><IconButton icon={Filter} variant="secondary" accessibilityLabel="Filtros" onPress={()=>setFilter(true)}/></View><View style={s.cards}>{filtrados.map(m=><Pressable key={m.id} onPress={()=>{LayoutAnimation.configureNext({duration:360,create:{type:LayoutAnimation.Types.easeInEaseOut,property:LayoutAnimation.Properties.opacity},update:{type:LayoutAnimation.Types.easeInEaseOut},delete:{type:LayoutAnimation.Types.easeInEaseOut,property:LayoutAnimation.Properties.opacity}});setExpanded(expanded===m.id?null:m.id)}} style={[s.compactCard,{backgroundColor:c.backgroundSecondary,borderColor:c.border}]}><View style={s.cardTop}><View style={{flex:1}}><ThemedText style={s.cardTitle}>{m.tipo_transaccion?.codigo??(es?"INGRESO":"EGRESO")} #{m.id}</ThemedText><ThemedText numberOfLines={1} style={[s.cardSub,{color:c.textSecondary}]}>{m.tipo_transaccion?.transaccion??m.detalle}</ThemedText></View><View style={s.cardRight}><ThemedText style={[s.amount,{color:c.primary}]}>Bs. {num(m.monto).toFixed(2)}</ThemedText>{expanded===m.id?<ChevronUp size={18} color={c.textSecondary}/>:<ChevronDown size={18} color={c.textSecondary}/>}</View></View>{expanded===m.id?<View style={[s.expand,{borderTopColor:c.border}]}><KV k="Fecha" v={String(m.fecha_registro).slice(0,16).replace("T"," ")}/><KV k="Detalle" v={m.detalle}/><KV k="Pago" v={m.tipo_pago}/><KV k="Estado" v={m.estado}/><View style={[s.expandedActions,{borderTopColor:c.border}]}><IconButton icon={Printer} size="md" variant="secondary" accessibilityLabel="Imprimir" onPress={()=>setPrint(m)}/>{m.estado==="Valido"?<IconButton icon={Ban} size="md" variant="secondary" accessibilityLabel="Anular" onPress={async()=>{const ok=await confirm.ask({title:"Anular movimiento",message:`¿Anular registro #${m.id}?`,variant:"warning",confirmText:"Anular"});if(ok)await h.anular(m.id);confirm.closeConfirm()}}/>:null}</View></View>:null}</Pressable>)}</View>
 <Modal visible={filter} onClose={()=>setFilter(false)} title={`Filtrar ${es?"ingresos":"egresos"}`}><Select<TipoPago|""> label="Tipo de pago" value={h.tipoPago} options={[{label:"Todos",value:""},{label:"Efectivo",value:"Efectivo"},{label:"Tarjeta",value:"Tarjeta"},{label:"QR",value:"QR"},{label:"Transferencia",value:"Transferencia"}]} onValueChange={v=>{h.setTipoPago(v);h.setPage(1)}} modalTitle="Tipo de pago"/><View style={{height:10}}/><Select<EstadoMovimiento|""> label="Estado" value={h.estado} options={[{label:"Todos",value:""},{label:"Valido",value:"Valido"},{label:"Anulado",value:"Anulado"}]} onValueChange={v=>{h.setEstado(v);h.setPage(1)}} modalTitle="Estado"/><View style={{height:12}}/><Button title="Ver resultados" onPress={()=>setFilter(false)}/></Modal><MovimientoFormModal visible={form} tipo={es?"Ingreso":"Egreso"} saving={h.saving} onClose={()=>setForm(false)} onSave={h.crear}/><MovimientoPrintModal visible={print!==null} kind={kind} movimiento={print} onClose={()=>setPrint(null)}/><ConfirmModal state={confirm.confirmState} busy={confirm.confirmBusy} onCancel={confirm.handleCancel} onConfirm={confirm.handleConfirm}/></View>
}

function TiposMobile(){const {theme}=useTheme();const c=theme.colors;const h=useTiposTransaccion();const [expanded,setExpanded]=useState<number|null>(null);const [modal,setModal]=useState(false);const [actual,setActual]=useState<TipoTransaccion|null>(null);const confirm=useConfirmLocal();return <View style={s.section}><View style={s.mobileToolbar}><View><ThemedText style={s.listTitle}>Tipos de transacción</ThemedText><ThemedText style={{color:c.textSecondary,fontSize:12}}>{h.total} registros</ThemedText></View><View style={s.actionRow}><IconButton icon={RefreshCw} size="sm" variant="secondary" accessibilityLabel="Actualizar" onPress={()=>void h.refrescar()}/><IconButton icon={Plus} variant="primary" accessibilityLabel="Nuevo tipo" onPress={()=>{setActual(null);setModal(true)}}/></View></View><View style={s.searchRow}><View style={{flex:1}}><SearchBar value={h.buscar} onChangeText={h.setBuscar} placeholder="Código o nombre..."/></View></View><View style={s.cards}>{h.items.map(t=><Pressable key={t.id} onPress={()=>{LayoutAnimation.configureNext({duration:360,create:{type:LayoutAnimation.Types.easeInEaseOut,property:LayoutAnimation.Properties.opacity},update:{type:LayoutAnimation.Types.easeInEaseOut},delete:{type:LayoutAnimation.Types.easeInEaseOut,property:LayoutAnimation.Properties.opacity}});setExpanded(expanded===t.id?null:t.id)}} style={[s.compactCard,{backgroundColor:c.backgroundSecondary,borderColor:c.border}]}><View style={s.cardTop}><View style={{flex:1}}><ThemedText style={s.cardTitle}>{t.codigo}</ThemedText><ThemedText style={[s.cardSub,{color:c.textSecondary}]}>{t.transaccion}</ThemedText></View><Badge label={t.tipo_transaccion} variant={t.tipo_transaccion==="Ingreso"?"success":"warning"}/></View>{expanded===t.id?<View style={[s.expand,{borderTopColor:c.border}]}><KV k="Código" v={t.codigo}/><KV k="Nombre" v={t.transaccion}/><KV k="Naturaleza" v={t.tipo_transaccion}/><View style={[s.expandedActions,{borderTopColor:c.border}]}><IconButton icon={Pencil} size="md" variant="secondary" accessibilityLabel="Editar" onPress={()=>{setActual(t);setModal(true)}}/><IconButton icon={Trash2} size="md" variant="destructive" accessibilityLabel="Eliminar" onPress={async()=>{const ok=await confirm.ask({title:"Eliminar tipo",message:`¿Eliminar ${t.codigo}?`,variant:"danger",confirmText:"Eliminar"});if(ok)await h.eliminar(t.id);confirm.closeConfirm()}}/></View></View>:null}</Pressable>)}</View><TipoTransaccionFormModal visible={modal} actual={actual} saving={h.saving} onClose={()=>setModal(false)} onSave={async p=>{const ok=actual?await h.guardar(p,actual.id):await h.guardar(p);if(ok)setModal(false);return ok}}/><ConfirmModal state={confirm.confirmState} busy={confirm.confirmBusy} onCancel={confirm.handleCancel} onConfirm={confirm.handleConfirm}/></View>}

const s=StyleSheet.create({root:{flex:1},page:{padding:12,gap:12,paddingBottom:90},head:{borderWidth:1,borderRadius:16,padding:12,flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:8},headLeft:{flexDirection:"row",alignItems:"center",gap:9,flex:1},iconBox:{width:38,height:38,borderRadius:11,alignItems:"center",justifyContent:"center"},headTitle:{fontSize:18,fontWeight:"900"},headSub:{fontSize:11,marginTop:1},headActions:{flexDirection:"row",gap:6,alignItems:"center"},section:{gap:10},dateRow:{flexDirection:"row",gap:6,alignItems:"center"},dateChip:{height:38,paddingHorizontal:13,borderRadius:19,borderWidth:1,alignItems:"center",justifyContent:"center"},searchRow:{flexDirection:"row",gap:8,alignItems:"center"},cards:{gap:8},compactCard:{borderWidth:1,borderRadius:13,padding:12},cardTop:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:8},cardMain:{flexDirection:"row",alignItems:"center",gap:10,flex:1},cardRight:{alignItems:"flex-end",gap:5,flexDirection:"row"},cardTitle:{fontSize:14,fontWeight:"900"},cardSub:{fontSize:11,marginTop:2},amount:{fontSize:13,fontWeight:"900"},expand:{borderTopWidth:1,marginTop:10,paddingTop:9,gap:7},kv:{flexDirection:"row",justifyContent:"space-between",gap:12},kvv:{fontSize:12,fontWeight:"800",textAlign:"right",flex:1},actionRow:{flexDirection:"row",gap:7,justifyContent:"flex-end",alignItems:"center"},expandedActions:{borderTopWidth:1,marginTop:3,paddingTop:9,flexDirection:"row",gap:8,justifyContent:"center",alignItems:"center",flexWrap:"wrap"},pager:{paddingVertical:4,alignItems:"center"},mobileToolbar:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",gap:8},listTitle:{fontSize:17,fontWeight:"900"},totalBar:{borderWidth:1,borderRadius:13,padding:12,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},totalText:{fontSize:19,fontWeight:"900"},floatingArqueo:{position:"absolute",right:16,bottom:16,minHeight:52,borderRadius:16,paddingHorizontal:18,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:9,elevation:8,shadowColor:"#000",shadowOpacity:.22,shadowRadius:8,shadowOffset:{width:0,height:4}},floatingArqueoText:{color:"#fff",fontSize:14,fontWeight:"900"},fixedTotal:{position:"absolute",left:0,right:0,bottom:0,minHeight:72,borderTopWidth:1,paddingHorizontal:20,paddingVertical:12,flexDirection:"row",alignItems:"center",justifyContent:"space-between",elevation:10,shadowColor:"#000",shadowOpacity:.12,shadowRadius:8,shadowOffset:{width:0,height:-3}}});
