import { ThemedText } from "@/components/ThemedText";
import { Printer } from "@/components/Printer";
import { Button } from "@/components/ui/Button";
import { Modal } from "@/components/ui/Modal";
import { useTheme } from "@/theme/useTheme";
import React, { useCallback, useEffect, useState } from "react";
import { Platform, ScrollView, StyleSheet, useWindowDimensions, View } from "react-native";
import Toast from "react-native-toast-message";

interface Props { visible:boolean; title:string; html:string; loading?:boolean; onClose:()=>void; }
export function EncomiendaPrintPreviewModal({visible,title,html,loading=false,onClose}:Props){
 const {theme}=useTheme();const c=theme.colors;const {width:windowWidth,height:windowHeight}=useWindowDimensions();const isMobile=windowWidth<768;
 const [animandoEntrada,setAnimandoEntrada]=useState(false);const paperWidth=isMobile?Math.min(286,Math.max(230,windowWidth-76)):302;const paperHeight=Math.round(paperWidth*1.25);const previewHeight=isMobile?Math.min(500,Math.max(360,windowHeight-280)):650;
 useEffect(()=>{if(!visible||loading||!html){setAnimandoEntrada(false);return;}setAnimandoEntrada(true);const t=setTimeout(()=>setAnimandoEntrada(false),1750);return()=>clearTimeout(t)},[visible,loading,html]);
 const imprimir=useCallback(()=>{if(Platform.OS!=="web"||loading||!html)return;try{const blob=new Blob([html],{type:"text/html"});const url=URL.createObjectURL(blob);const win=window.open(url,"_blank","width=400,height=600");if(!win)throw new Error("El navegador bloqueó la pestaña. Permite ventanas emergentes e inténtalo de nuevo.");setTimeout(()=>URL.revokeObjectURL(url),60000);}catch(error:any){Toast.show({type:"error",text1:"No se pudo imprimir",text2:error?.message||"Intenta nuevamente."})}},[html,loading]);
 const ticketFrame=Platform.OS==="web"&&html?React.createElement("iframe" as any,{srcDoc:html,title,style:{width:"100%",height:"100%",border:"0",backgroundColor:"#FFFFFF",display:"block"}}):null;
 return <Modal visible={visible} title={title} onClose={onClose} maxWidth={900} contentPadding={isMobile?12:20} scrollable={false} footer={<View style={[styles.footer,isMobile&&styles.footerMobile]}><Button title="Cerrar" variant="secondary" onPress={onClose} disabled={loading}/><Button title="Imprimir" onPress={imprimir} disabled={loading||!html} loading={loading}/></View>}>
  <View style={styles.content}><View style={styles.header}><ThemedText style={styles.title}>Vista previa de impresión</ThemedText><ThemedText style={[styles.description,{color:c.textSecondary}]}>Verifica la etiqueta antes de enviarla a la impresora.</ThemedText></View>
  <View style={[styles.animationContainer,isMobile&&styles.animationContainerMobile,{height:previewHeight,backgroundColor:c.background,borderColor:c.border}]}><ScrollView style={styles.previewScroll} contentContainerStyle={[styles.previewScrollContent,isMobile&&styles.previewScrollContentMobile]} showsVerticalScrollIndicator>
   <Printer.Root stage={animandoEntrada?"printing":"complete"} paperSize="custom" customPaper={{aspectRatio:paperWidth/paperHeight,minHeight:paperHeight,serrated:true}} printingDuration={1650} machineMaxWidth={520} paperWidth={paperWidth} outputHeight={paperHeight+150}><Printer.Machine><Printer.Header><View style={[styles.brand,{backgroundColor:c.primary}]}><ThemedText style={[styles.brandText,{color:c.primaryForeground}]}>C</ThemedText></View><ThemedText style={styles.machineTitle}>Etiqueta QR de encomienda</ThemedText></Printer.Header><Printer.Screen><Printer.Status>{animandoEntrada?"Imprimiendo vista previa…":"Etiqueta lista para imprimir"}</Printer.Status></Printer.Screen></Printer.Machine><Printer.Output><Printer.Paper><View style={[styles.ticketPreview,{width:paperWidth,height:paperHeight}]}>{ticketFrame}</View></Printer.Paper></Printer.Output></Printer.Root>
  </ScrollView></View></View></Modal>;
}
const styles=StyleSheet.create({content:{gap:14},header:{gap:4},title:{fontSize:16,fontWeight:"800"},description:{fontSize:13,lineHeight:18},animationContainer:{width:"100%",height:650,borderWidth:1,borderRadius:14,overflow:"hidden"},animationContainerMobile:{borderRadius:12},previewScroll:{width:"100%",height:"100%"},previewScrollContent:{minHeight:650,paddingHorizontal:18,paddingTop:22,paddingBottom:34,alignItems:"center",justifyContent:"flex-start"},previewScrollContentMobile:{minHeight:0,paddingHorizontal:8,paddingTop:14,paddingBottom:24},brand:{width:34,height:34,borderRadius:9,alignItems:"center",justifyContent:"center"},brandText:{fontSize:18,fontWeight:"900"},machineTitle:{fontSize:13,fontWeight:"800"},ticketPreview:{alignSelf:"center",backgroundColor:"#FFFFFF",overflow:"hidden"},footer:{flexDirection:"row",justifyContent:"flex-end",gap:10,flexWrap:"wrap"},footerMobile:{width:"100%"}});
